### ISSUE TITLE
Unable to use jsonb_accessor scopes to find fields that are nil

### ISSUE THREAD

**Issue by Velora** [madeintandem/jsonb_accessor#159]
I expected the following would work: 

```Account.stats_data_where_not(my_stat: nil)```
```Account.stats_data_where(my_stat: nil)```

Instead the first returns all records including those where the field is nil, and the second includes no records

```my_stat``` is declared in the following way: 
```
jsonb_accessor :stats_data,
                my_stat: :string
```
Other scopes such as ```Account.stats_data_where(my_stat: "Test")``` work as expected.

I am using Postgres 13. 

Looking through the issues here, I have seen others mentioning similar scopes, so I was under the impression this would work. I appreciate this gem and any suggestions you might have.

**Comment by haffla** [comment]
Hello @Velora,

that's because there are basically three different concepts of null/nil at play here. You have the Ruby concept of `nil`, you have JSON `null` and you have relational database concept of `null`.

```ruby
Account.stats_data_where(my_stat: nil)
```

what do you expect from this? You want all records where `stats_data` doesn't have `my_stat`, where it is `null` in the Postgres definition of `null`, where it doesn't exist. But what this really is translated to is:

```sql
where stats_data @> ('{ "my_stat": null }')::jsonb
```

It's trying to find all records where the `stats_data` JSON value has a key `my_stats` that is equal to the JSON value of `null`. You can test this: take some account in your database and do `account.update!(my_stat: nil)`. Now run the query again and it will work.

What you are looking for is "find all records where `my_stat` is the JSON value `null` OR where it doesn't exist". The latter you could write as

```ruby
Account.where.not("stats_data ? 'my_stat'")
```

Alternatively you can do in your model

```ruby
jsonb_accessor :stats_data,
                my_stat: [:string, default: nil]
```

Now each time you create an account it will be saved explicitly with the JSON `{ "my_stat": null }` and `Account.stats_data_where(my_stat: nil)` will return those.

I am thinking about adding a more scopes to this gem like

`stats_data_where_has_key` which would create SQL that does what you want.

**Comment by haffla** [comment]
For Ruby there is no difference between `{ a: nil }` and `{}`. In both cases if you do `hash[:a]` it will return `nil`. Javascript/JSON is different here.

```ruby
Account.stats_data_where(my_stat: nil)
```

is NOT about returning where the Ruby object's `my_stat` method returns `nil`.

**Comment by Velora** [comment]
Thanks @haffla ```Account.where.not("stats_data ? 'my_stat'")``` was what I needed and works as expected.
